### ISSUE TITLE
Allow to set ucode

### ISSUE THREAD

**Issue by kratnor** [maximbaz/arch-secure-boot#1]
Hello, 
I follow your great dotfiles and wanted to ask you, if you could add support for AMD ucode as well. 
Something like that would probably be enough:
https://github.com/gdamjan/secure-boot/blob/master/secure-boot#L17

Thanks for all your great projects!

**Comment by maximbaz** [comment]
Hello, thanks for the kind words and the suggestion! 

I went for a simpler alternative of just using any available `-ucode` image, that way a configuration is not needed and pacman hook works as well out of the box.

Do let me know about your experience if you end up using this project, I'm still experimenting with it and many things are very much tailored to my own dotfiles, with some things intentionally not configurable (e.g. pulling linux-lts image to build a safe-safe recovery image, when everything else fails).
