### ISSUE TITLE
Does the tool support booting read-only snapshots in overlayfs mode?

### ISSUE THREAD

**Issue by developer91234** [maximbaz/arch-secure-boot#27]
This is something present in grub-btrfs but I'd prefer a simpler tool because grub is too much of a black hole.

**Comment by maximbaz** [comment]
To be honest I don't know what an overlayfs is, this tool will simply boot in your snapshot, and if your snapshot is readonly, then it will remain readonly...

**Comment by developer91234** [comment]
To be honest, I don't know either - otherwise I'd implement it myself lol - but here is the implementation:
https://github.com/Antynea/grub-btrfs/blob/master/initramfs/readme.md

Apparently it's the only foolproof way to boot btrfs snapshots.

**Comment by maximbaz** [comment]
Thanks for the link, no this is not supported then, this simply boots into whatever snapshot you have. I don't doing overlayfs is in scope for this project to be honest, I was always able to boot into a readonly snapshot and fix my system when I needed to.

**Comment by maximbaz** [comment]
Closing for now, but if you or anyone else wants to continue discussing this idea, please just continue posting here on in a new thread. Thanks!
